import { useContext, useEffect,useState } from "react";
import { AuthContext } from "../context/AuthContext";
export default function savedItinerary() {
    const {user}=useContext(AuthContext);
    const [itinerary, setItinerary] = useState([]);
    
    const [loading, setLoading] = useState(true);
    useEffect(()=>{
        const fetchItineraries = async () => {
            try {
              const response = await fetch("/api/ai/savedIter");
              const data = await response.json();
              setItinerary(data.iters);
            } catch (error) {
              console.error("Error fetching itineraries:", error);
            } finally {
              setLoading(false);
            }
          };
          fetchItineraries();
    },[]);
    return (
        <div className=" min-h-screen p-6 bg-black text-white rounded-lg font-mono">
          <h1 className="text-2xl text-center font-bold mb-4">Saved Itineraries</h1>
    
          {loading ? (
            <p>Loading itineraries...</p>
          ) : (
            <div className="grid md:grid-cols-2 gap-6">
              {itinerary.map((iter) => (
                <div key={iter._id} className="border shadow-md rounded-lg p-4">
                  <h2 className="text-xl font-semibold">{iter.destination}</h2>
                  <p>{iter.days} days</p>
                  <p className="text-sm text-gray-500">generated by: {user?user.name:"Anonymous"}</p>
                  <p className="text-sm text-gray-500">{new Date(iter.createdAt).toLocaleDateString()}</p>
                  <p className="mt-2">{iter.itinerary}</p>
                </div>
              ))}
            </div>
          )}
        </div>
      );
}